const CATALOG = [
    {
        id: 'el1',
        category_mus: 'guitar',
        category_man: 'dimebag-darrell',
        name: '1981 Dean ML - "The Dean from Hell"',
        img: 'img/dimebag-darrell/1981-dean-from-hell-xl.png',
        price: 50000,
    },
    {
        id: 'el2',
        category_mus: 'guitar',
        category_man: 'dimebag-darrell',
        name: 'Dean Dimebag Concrete Sledge ML - Reversed Headstock',
        img: 'img/dimebag-darrell/dean-dimebag-concrete-sledge-ml-reversed-headstock-xl.png',
        price: 60000,
    },
    {
        id: 'el3',
        category_mus: 'accessory',
        category_man: 'dimebag-darrell',
        name: 'Dunlop Tortex Standard 0.88mm Guitar Picks (50шт.)',
        img: 'img/dimebag-darrell/dunlop-tortex-standard-0-88mm-guitar-picks-xl.png',
        price: 2000,
    },
    {
        id: 'el4',
        category_mus: 'pedal',
        category_man: 'dimebag-darrell',
        name: 'MXR 6-Band Graphic Equalizer',
        img: 'img/dimebag-darrell/mxr-6-band-graphic-equalizer-xl.png',
        price: 8000,
    },
    {
        id: 'el5',
        category_mus: 'amp',
        category_man: 'dimebag-darrell',
        name: 'Randall Warhead 2CH 300 Watt Amp Head',
        img: 'img/dimebag-darrell/randall-warhead-2ch-300-watt-amp-head-xl.png',
        price: 12000,
    },
    {
        id: 'el6',
        category_mus: 'microphon',
        category_man: 'sadfds',
        name: '1981 Dean ML - "The Dean from Hell"',
        img: 'img/dimebag-darrell/dean-dimebag-concrete-sledge-ml-reversed-headstock-xl.png',
        price: 40000,
    },
    {
        id: 'el7',
        category_mus: 'microphon',
        category_man: 'dgfgsfd',
        name: '1981 Dean ML - "The Dean from Hell"',
        img: 'img/dimebag-darrell/dean-dimebag-concrete-sledge-ml-reversed-headstock-xl.png',
        price: 40000,
    },
    {
        id: 'el8',
        category_mus: 'microphon',
        category_man: '213213',
        name: '1981 Dean ML - "The Dean from Hell"',
        img: 'img/dimebag-darrell/dean-dimebag-concrete-sledge-ml-reversed-headstock-xl.png',
        price: 40000,
    },
    {
        id: 'el9',
        category_mus: 'microphon',
        category_man: '213213',
        name: '1981 Dean ML - "The Dean from Hell"',
        img: 'img/dimebag-darrell/dean-dimebag-concrete-sledge-ml-reversed-headstock-xl.png',
        price: 40000,
    },
    {
        id: 'el10',
        category_mus: 'microphon',
        category_man: '213213',
        name: '1981 Dean ML - "The Dean from Hell"',
        img: 'img/dimebag-darrell/dean-dimebag-concrete-sledge-ml-reversed-headstock-xl.png',
        price: 40000,
    },
];